### ISSUE TITLE
.eslintcache file should not be pushed to github.

### ISSUE THREAD

**Issue by vivek80801** [vinaykumargb/react-weather-app#1]
new react-app has a bug. it keep producing **.eslintcache** file. **.eslintcache** file exposes our file system to the world.

May be react team will fix this in future release.

Solution: write ".eslintcache" in your .gitignore file.

**Comment by vinaykumargb** [comment]
Many thanks for letting me know about this issue, and for the solution. I didn't know about this issue before, though. However, I make sure to include that file in my  **.gitignore** of my future react projects. :)
